// type 1 - GPIO, 0 - GND, 2 - POWER
export const PINS = [
    { 
        'name':'GP0',
        'physical':1,
        'type':1,
        'support':['UART0 TX', 'I2C0 SDA', 'SPI0 RX']
    },
    { 
        'name':'GP1',
        'physical':2,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':3,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP2',
        'physical':4,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP3',
        'physical':5,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP4',
        'physical':6,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP5',
        'physical':7,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':8,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP6',
        'physical':9,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP7',
        'physical':10,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP8',
        'physical':11,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP9',
        'physical':4,
        'type':12,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':13,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP10',
        'physical':14,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP11',
        'physical':15,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP12',
        'physical':16,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP13',
        'physical':17,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':4,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP14',
        'physical':19,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP15',
        'physical':20,
        'type':1,
        'support':[]
    },
    { 
        'name':'VBUS',
        'physical':40,
        'type':2,
        'support':[]
    },    
    { 
        'name':'VSYS',
        'physical':39,
        'type':2,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':38,
        'type':0,
        'support':[]
    },    
    { 
        'name':'3V3 En',
        'physical':37,
        'type':1,
        'support':[]
    },    
    { 
        'name':'3V3 Out',
        'physical':36,
        'type':2,
        'support':[]
    },    
    { 
        'name':'ADC VRef',
        'physical':35,
        'type':5,
        'support':[]
    },    
    { 
        'name':'GP28/A2',
        'physical':34,
        'type':1,
        'support':[]
    },    
    { 
        'name':'ADC GND',
        'physical':33,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP27/A1',
        'physical':32,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP26/A0',
        'physical':31,
        'type':1,
        'support':[]
    },    
    { 
        'name':'RUN',
        'physical':30,
        'type':3,
        'support':[]
    },    
    { 
        'name':'GP22',
        'physical':29,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':28,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP21',
        'physical':27,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP20',
        'physical':26,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP19',
        'physical':25,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP18',
        'physical':24,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GND',
        'physical':23,
        'type':0,
        'support':[]
    },    
    { 
        'name':'GP17',
        'physical':22,
        'type':1,
        'support':[]
    },    
    { 
        'name':'GP16',
        'physical':21,
        'type':1,
        'support':[]
    }
]